version: 1
schema:
  type: object
  required:
    - version
    - task_id
    - tier
    - contracts
  properties:
    version:
      type: integer
    task_id:
      type: string
    tier:
      type: object
    links:
      type: object
    contracts:
      type: object
    properties:
      type: object
    observability:
      type: object
